CREATE TABLE car_info (
	MODEL_CODE INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(20) NOT NULL
	, MODEL_PRICE INT NOT NULL
	, MODEL_MAKER VARCHAR(20) NOT NULL
);

SELECT * FROM car_info;

CREATE TABLE sales_info (
	SALE_CODE INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_BUYER VARCHAR(20) NOT NULL
	, BUYER_TEL VARCHAR(20) NOT NULL
	, MODEL_COLOR VARCHAR(10) NOT NULL
	, SALE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, MODEL_CODE INT NOT NULL REFERENCES CAR_INFO (MODEL_CODE)
); 

SELECT * FROM SALES_INFO;